mkdir en-as
mkdir en-bn
mkdir en-gom
mkdir en-gu
mkdir en-hi
mkdir en-kn
mkdir en-ks
mkdir en-mai
mkdir en-ml
mkdir en-mr
mkdir en-ne
mkdir en-or
mkdir en-pa
mkdir en-sa
mkdir en-sd
mkdir en-si
mkdir en-ta
mkdir en-te
mkdir en-ur



mkdir en-as/corpus
mkdir en-bn/corpus
mkdir en-gom/corpus
mkdir en-gu/corpus
mkdir en-hi/corpus
mkdir en-kn/corpus
mkdir en-ks/corpus
mkdir en-mai/corpus
mkdir en-ml/corpus
mkdir en-mr/corpus
mkdir en-ne/corpus
mkdir en-or/corpus
mkdir en-pa/corpus
mkdir en-sa/corpus
mkdir en-sd/corpus
mkdir en-si/corpus
mkdir en-ta/corpus
mkdir en-te/corpus
mkdir en-ur/corpus
